# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer


def preprocess_data(
    input_path: str,
    output_dir: str,
    test_size: float = 0.2,
    random_state: int = 42
):
    # 1) Load dataset
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"File tidak ditemukan: {input_path}")

    df = pd.read_csv(input_path)

    # 2) Clean column names
    df.columns = (
        df.columns.str.strip()
        .str.replace(r"[\s\-]+", "_", regex=True)
        .str.replace(r"[^\w]", "", regex=True)
        .str.lower()
    )

    # 3) Validasi kolom wajib
    required_cols = {"churn", "totalcharges"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Kolom wajib hilang: {missing}. Cek header CSV kamu.")

    # 4) Drop duplicate rows
    df = df.drop_duplicates()

    # 5) Drop ID column (kalau ada)
    if "customerid" in df.columns:
        df = df.drop(columns=["customerid"])

    # 6) Convert totalcharges to numeric (spasi/kosong jadi NaN)
    df["totalcharges"] = pd.to_numeric(df["totalcharges"], errors="coerce")

    # 7) Encode target churn dengan validasi anti-NaN
    #    (kalau ada nilai selain yes/no akan terdeteksi)
    churn_raw = df["churn"].astype(str).str.strip().str.lower()
    df["churn"] = churn_raw.map({"no": 0, "yes": 1})

    if df["churn"].isnull().any():
        bad_values = churn_raw[df["churn"].isnull()].unique()
        raise ValueError(
            f"Nilai 'churn' tidak terduga (bukan Yes/No): {bad_values}. "
            "Periksa isi kolom churn pada dataset."
        )

    # 8) Split features and target
    X = df.drop(columns=["churn"])
    y = df["churn"].astype(int)

    # 9) Identify column types
    num_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
    cat_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()

    # 10) Pipelines
    numeric_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])

    categorical_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_pipe, num_cols),
            ("cat", categorical_pipe, cat_cols)
        ],
        remainder="drop"
    )

    # 11) Train-test split (stratify aman karena y sudah 0/1 tanpa NaN)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=random_state,
        stratify=y
    )

    # 12) Transform
    X_train_enc = preprocessor.fit_transform(X_train)
    X_test_enc = preprocessor.transform(X_test)

    # 13) Save outputs
    os.makedirs(output_dir, exist_ok=True)

    pd.DataFrame(X_train_enc).to_csv(os.path.join(output_dir, "X_train.csv"), index=False)
    pd.DataFrame(X_test_enc).to_csv(os.path.join(output_dir, "X_test.csv"), index=False)
    y_train.to_csv(os.path.join(output_dir, "y_train.csv"), index=False)
    y_test.to_csv(os.path.join(output_dir, "y_test.csv"), index=False)

    print("Preprocessing automation completed successfully")
    print(f"Saved to: {output_dir}/")
    print(f"Train shape: {X_train_enc.shape} | Test shape: {X_test_enc.shape}")


if __name__ == "__main__":
    preprocess_data(
        input_path="Telco_Customer_Churn.csv",
        output_dir="Telco_Customer_preprocessing"
    )

import os
os.listdir("Telco_Customer_preprocessing")